# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/freebsd-11.1"
  config.vm.guest = :freebsd
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.shell = "/bin/sh"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "2048"
  end

  config.vm.provision "shell", inline: <<-SHELL
    # set hostname
    sysrc hostname=devbox.local
    # also set it for first boot
    hostname devbox.local

    # change home directory
    cd /
    mv /home/vagrant /usr/home/
    rmdir /home
    ln -s /usr/home /home
    pw usermod vagrant -d /usr/home/vagrant
    cd

    # set UTF-8
    cat <<EOF >>/etc/login.conf
utf8|UTF-8 Encoding:\\\\
  :charset=utf-8:\\\\
  :lang=en_US.UTF-8:\\\\
  :tc=default:
EOF
    cap_mkdb /etc/login.conf
    pw usermod vagrant -L utf8

    # install software
    pkg update
    # install salt
    pkg install -y py27-salt

    # general tools
    pkg install -y git mksh tmux vim-lite

    # the vm will be used interactively, so change the default shell
    pw usermod vagrant -s /usr/local/bin/mksh

    # C and C++
    pkg install -y cmake llvm40 ninja

    # Go
    pkg install -y go

    # Python
    pkg install -y python36 py36-mypy py36-pyflakes

  SHELL
end
