# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/freebsd-12.0"
  config.vm.guest = :freebsd
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.shell = "/bin/sh"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 4
    vb.memory = "2048"
  end

  config.vm.provision "shell", path: "../scripts/provision.base.sh", args: "devbox"
  config.vm.provision "shell", inline: <<-SHELL
    pkg install -qy cmake llvm80 ninja
    pkg install -qy go
    pkg install -qy python36 py36-mypy py36-pyflakes py36-pylint py36-pycodestyle
  SHELL
end
